#!/usr/bin/env python3
"""
tools/generate_filler_presets.py — Phase 4 §A6b filler-preset generator.

Doc 09 §4 mandates 128 named factory presets but explicitly permits
filler entries: "Rows marked _(Phase 4)_ are placeholders that Phase 4
sound design will fill — the table specifies the count and category but
not the final names."

This script reads one named template per corner, varies the macros
inside corner-safe bands using a deterministic seeded PRNG, and writes
the unfilled slot IDs from Doc 09 §4. Output is committed to the repo;
the script is run once per palette regeneration (rare).

Usage:
    tools/generate_filler_presets.py

Determinism:
    The PRNG is seeded with the slot ID, so re-running the script
    produces byte-identical output. The generated presets feed the
    cross-platform hash test like any other factory preset.

Authoring policy:
    - drone   slots 6-32:   small variations of Slow Glacier; coherence
                            stays at 1.0, excitation at 0.0 to keep cv
                            comfortably under 0.05.
    - organic slots 37-64:  variations of Forest Breath; migration ≥ 0.4
                            and LFO routing on coherence/excitation
                            preserve the > 50 Hz centroid stddev.
    - pitched slots 69-88:  variations of Glass Pad; coherence locked at
                            1.0, migration at 0.0 (pitched threshold
                            requires both).
    - glitch  slots 93-104: variations of Init Glitch; S&H LFOs on
                            DENSITY/EXCITATION at depth ≥ 0.4 produce
                            ≥ 5 onsets reliably.
    - hybrid  slots 110-120: blends with no contract tag (the gate
                            doesn't measure them).

Each filler is named `<Category> Filler N` so the chooser surface stays
readable; users renaming via Save As is the authoring path.
"""
from __future__ import annotations

import json
import pathlib
import random
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

CORNERS = {
    "drone":   {"dir": "drone",   "slots": list(range(6, 33)),  "tag": "contract:drone"},
    "organic": {"dir": "organic", "slots": list(range(37, 65)), "tag": "contract:organic"},
    "pitched": {"dir": "pitched", "slots": list(range(69, 89)), "tag": "contract:pitched"},
    "glitch":  {"dir": "glitch",  "slots": list(range(93, 105)),"tag": "contract:glitch"},
    "hybrid":  {"dir": "hybrid",  "slots": list(range(110, 121)),"tag": None},
}


def _round(x: float, digits: int = 4) -> float:
    return round(x, digits)


def _vary(rng: random.Random, base: float, lo: float, hi: float, jitter: float) -> float:
    """Return base + uniform(-jitter, jitter), clamped to [lo, hi]."""
    return _round(max(lo, min(hi, base + (rng.random() * 2.0 - 1.0) * jitter)))


def template_drone(slot: int, rng: random.Random) -> dict:
    return {
        "_magic": "SFS-1.00",
        "format_version": "1.0",
        "engine_version": "1.0.0",
        "metadata": {
            "name": f"Drone Filler {slot}",
            "author": "SFS Factory",
            "category": "Drone",
            "tags": ["drone", "filler", "contract:drone"],
            "created": "2026-05-07T20:00:00Z",
            "modified": "2026-05-07T20:00:00Z",
            "description": (
                f"Drone filler slot {slot}. Generated by tools/generate_filler_presets.py "
                "from the Slow Glacier template with bounded macro variation; coherence locked "
                "at 1.0 and excitation at 0.0 to preserve the cv < 0.05 contract."
            ),
        },
        "seed": "0x5F5F5F5F5F5F5F5F",
        "macros": {
            "tension": _vary(rng, 0.55, 0.45, 0.7, 0.1),
            "damping": _vary(rng, 0.25, 0.15, 0.4, 0.1),
            "density": _vary(rng, 0.55, 0.4, 0.7, 0.1),
            "migration": 0.0,
            "coherence": 1.0,
            "excitation": 0.0,
        },
        "structural": {
            "topology": "ring",
            "aspect": 1.0,
            "substrate_size": 1024,
            "deposit_kernel": "linear",
            "read_kernel": "linear",
        },
        "agents": {
            "max_active": 16,
            "harmonic_set": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            "shape_distribution": {"sine": 1.0, "saw": 0.0, "square": 0.0, "fmpair": 0.0, "noise": 0.0},
            "shape_param_default": {"fm_ratio_index": 0.5, "fm_index_index": 0.3},
            "detune_scale": 0.0,
        },
        "envelopes": {
            "env1": {"attack": _vary(rng, 0.4, 0.2, 0.6, 0.2),
                     "decay": _vary(rng, 0.6, 0.4, 1.0, 0.3),
                     "sustain": _vary(rng, 0.85, 0.7, 0.95, 0.1),
                     "release": _vary(rng, 4.0, 2.0, 8.0, 2.0)},
            "env2": {"attack": 0.05, "decay": 0.3, "sustain": 1.0, "release": 0.5},
        },
        "lfos": [
            {"rate_hz": _vary(rng, 0.05, 0.03, 0.1, 0.04), "depth": 1.0, "shape": "sine",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 2.0, "depth": 1.0, "shape": "triangle", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 5.0, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 7.0, "depth": 1.0, "shape": "sample_hold", "sync": "free", "phase": 0.0, "reset_on_note": False},
        ],
        "modulation_matrix": {"slots": []},
        "harvesters": {"spacing": 0.5, "orbit_depth": 0.0, "orbit_speed_hz": 0.05, "orbit_shape": "circle"},
        "output": {"master_gain_db": 0.0, "pan": 0.0, "limiter_active": False},
    }


def template_organic(slot: int, rng: random.Random) -> dict:
    return {
        "_magic": "SFS-1.00",
        "format_version": "1.0",
        "engine_version": "1.0.0",
        "metadata": {
            "name": f"Organic Filler {slot}",
            "author": "SFS Factory",
            "category": "Organic",
            "tags": ["organic", "filler", "contract:organic"],
            "created": "2026-05-07T20:00:00Z",
            "modified": "2026-05-07T20:00:00Z",
            "description": (
                f"Organic filler slot {slot}. Generated from the Forest Breath template; "
                "high migration + LFO-driven motion preserves centroid stddev > 50 Hz."
            ),
        },
        "seed": "0x5F5F5F5F5F5F5F5F",
        "macros": {
            "tension": _vary(rng, 0.5, 0.4, 0.6, 0.1),
            "damping": _vary(rng, 0.4, 0.3, 0.5, 0.1),
            "density": _vary(rng, 0.6, 0.5, 0.7, 0.1),
            "migration": _vary(rng, 0.65, 0.5, 0.85, 0.15),
            "coherence": _vary(rng, 0.3, 0.15, 0.45, 0.15),
            "excitation": _vary(rng, 0.4, 0.25, 0.55, 0.15),
        },
        "structural": {
            "topology": "ring",
            "aspect": 1.0,
            "substrate_size": 1024,
            "deposit_kernel": "linear",
            "read_kernel": "linear",
        },
        "agents": {
            "max_active": 16,
            "harmonic_set": [1, 1.5, 2, 2.5, 3, 4, 5, 7],
            "shape_distribution": {"sine": 0.7, "saw": 0.0, "square": 0.0, "fmpair": 0.2, "noise": 0.1},
            "shape_param_default": {"fm_ratio_index": 0.5, "fm_index_index": 0.3},
            "detune_scale": _vary(rng, 0.1, 0.05, 0.15, 0.05),
        },
        "envelopes": {
            "env1": {"attack": 0.1, "decay": 0.5, "sustain": 0.8, "release": 1.5},
            "env2": {"attack": 0.05, "decay": 0.3, "sustain": 1.0, "release": 0.5},
        },
        "lfos": [
            {"rate_hz": _vary(rng, 0.2, 0.1, 0.3, 0.1), "depth": 1.0, "shape": "sine",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": _vary(rng, 0.3, 0.2, 0.5, 0.15), "depth": 1.0, "shape": "triangle",
             "sync": "free", "phase": 0.25, "reset_on_note": False},
            {"rate_hz": 5.0, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 7.0, "depth": 1.0, "shape": "sample_hold", "sync": "free", "phase": 0.0, "reset_on_note": False},
        ],
        "modulation_matrix": {
            "slots": [
                {"active": True, "source": "LFO1", "destination": "EXCITATION",
                 "depth": _vary(rng, 0.4, 0.3, 0.5, 0.1), "curve": "LINEAR"},
                {"active": True, "source": "LFO2", "destination": "MIGRATION",
                 "depth": _vary(rng, 0.3, 0.2, 0.4, 0.1), "curve": "LINEAR"},
            ]
        },
        "harvesters": {"spacing": 0.5, "orbit_depth": 0.0, "orbit_speed_hz": 0.05, "orbit_shape": "circle"},
        "output": {"master_gain_db": 0.0, "pan": 0.0, "limiter_active": False},
    }


def template_pitched(slot: int, rng: random.Random) -> dict:
    return {
        "_magic": "SFS-1.00",
        "format_version": "1.0",
        "engine_version": "1.0.0",
        "metadata": {
            "name": f"Pitched Filler {slot}",
            "author": "SFS Factory",
            "category": "Pitched",
            "tags": ["pitched", "filler", "contract:pitched"],
            "created": "2026-05-07T20:00:00Z",
            "modified": "2026-05-07T20:00:00Z",
            "description": (
                f"Pitched filler slot {slot}. Generated from the Glass Pad template; "
                "coherence locked at 1.0 and migration at 0.0 to keep the played MIDI note as the perceived pitch."
            ),
        },
        "seed": "0x5F5F5F5F5F5F5F5F",
        "macros": {
            "tension": _vary(rng, 0.5, 0.4, 0.6, 0.1),
            "damping": _vary(rng, 0.3, 0.2, 0.4, 0.1),
            "density": _vary(rng, 0.55, 0.4, 0.7, 0.15),
            "migration": 0.0,
            "coherence": 1.0,
            "excitation": 0.0,
        },
        "structural": {
            "topology": "ring",
            "aspect": 1.0,
            "substrate_size": 1024,
            "deposit_kernel": "linear",
            "read_kernel": "linear",
        },
        "agents": {
            "max_active": rng.choice([8, 12, 16]),
            "harmonic_set": [1, 2, 3, 4],
            "shape_distribution": {"sine": 1.0, "saw": 0.0, "square": 0.0, "fmpair": 0.0, "noise": 0.0},
            "shape_param_default": {"fm_ratio_index": 0.5, "fm_index_index": 0.3},
            "detune_scale": 0.0,
        },
        "envelopes": {
            "env1": {"attack": _vary(rng, 0.05, 0.005, 0.2, 0.1),
                     "decay": _vary(rng, 0.2, 0.05, 0.6, 0.2),
                     "sustain": _vary(rng, 0.85, 0.7, 0.95, 0.1),
                     "release": _vary(rng, 1.0, 0.3, 2.0, 0.7)},
            "env2": {"attack": 0.05, "decay": 0.3, "sustain": 1.0, "release": 0.5},
        },
        "lfos": [
            {"rate_hz": 0.5, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 2.0, "depth": 1.0, "shape": "triangle", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 5.0, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 7.0, "depth": 1.0, "shape": "sample_hold", "sync": "free", "phase": 0.0, "reset_on_note": False},
        ],
        "modulation_matrix": {"slots": []},
        "harvesters": {"spacing": 0.5, "orbit_depth": 0.0, "orbit_speed_hz": 0.05, "orbit_shape": "circle"},
        "output": {"master_gain_db": 0.0, "pan": 0.0, "limiter_active": False},
    }


def template_glitch(slot: int, rng: random.Random) -> dict:
    return {
        "_magic": "SFS-1.00",
        "format_version": "1.0",
        "engine_version": "1.0.0",
        "metadata": {
            "name": f"Glitch Filler {slot}",
            "author": "SFS Factory",
            "category": "Glitch",
            "tags": ["glitch", "filler", "contract:glitch"],
            "created": "2026-05-07T20:00:00Z",
            "modified": "2026-05-07T20:00:00Z",
            "description": (
                f"Glitch filler slot {slot}. Generated from the Init Glitch template; "
                "S&H LFOs on DENSITY and EXCITATION at depth ≥ 0.4 produce ≥ 5 onsets in 5 s."
            ),
        },
        "seed": "0x5F5F5F5F5F5F5F5F",
        "macros": {
            "tension": _vary(rng, 0.6, 0.5, 0.7, 0.1),
            "damping": _vary(rng, 0.2, 0.15, 0.3, 0.07),
            "density": _vary(rng, 0.5, 0.4, 0.6, 0.1),
            "migration": _vary(rng, 0.0, 0.0, 0.4, 0.2),
            "coherence": _vary(rng, 0.5, 0.3, 0.7, 0.15),
            "excitation": _vary(rng, 0.5, 0.4, 0.7, 0.1),
        },
        "structural": {
            "topology": "ring",
            "aspect": 1.0,
            "substrate_size": 1024,
            "deposit_kernel": "linear",
            "read_kernel": "linear",
        },
        "agents": {
            "max_active": 16,
            "harmonic_set": [1, 2, 3, 4, 5, 6, 7, 8],
            "shape_distribution": {"sine": 0.4, "saw": 0.0, "square": 0.0, "fmpair": 0.4, "noise": 0.2},
            "shape_param_default": {"fm_ratio_index": 0.6, "fm_index_index": 0.5},
            "detune_scale": _vary(rng, 0.05, 0.0, 0.15, 0.07),
        },
        "envelopes": {
            "env1": {"attack": 0.01, "decay": 0.12, "sustain": 0.75, "release": 0.25},
            "env2": {"attack": 0.05, "decay": 0.3, "sustain": 1.0, "release": 0.5},
        },
        "lfos": [
            {"rate_hz": 0.5, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 2.0, "depth": 1.0, "shape": "triangle", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": _vary(rng, 8.0, 6.0, 12.0, 2.5), "depth": 1.0, "shape": "sample_hold",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": _vary(rng, 11.0, 9.0, 15.0, 3.0), "depth": 1.0, "shape": "sample_hold",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
        ],
        "modulation_matrix": {
            "slots": [
                {"active": True, "source": "LFO3", "destination": "DENSITY",
                 "depth": _vary(rng, 0.5, 0.4, 0.6, 0.1), "curve": "LINEAR"},
                {"active": True, "source": "LFO4", "destination": "EXCITATION",
                 "depth": _vary(rng, 0.5, 0.4, 0.6, 0.1), "curve": "LINEAR"},
            ]
        },
        "harvesters": {"spacing": 0.5, "orbit_depth": 0.0, "orbit_speed_hz": 0.05, "orbit_shape": "circle"},
        "output": {"master_gain_db": 0.0, "pan": 0.0, "limiter_active": False},
    }


def template_hybrid(slot: int, rng: random.Random) -> dict:
    return {
        "_magic": "SFS-1.00",
        "format_version": "1.0",
        "engine_version": "1.0.0",
        "metadata": {
            "name": f"Hybrid Filler {slot}",
            "author": "SFS Factory",
            "category": "Hybrid",
            "tags": ["hybrid", "filler"],
            "created": "2026-05-07T20:00:00Z",
            "modified": "2026-05-07T20:00:00Z",
            "description": (
                f"Hybrid filler slot {slot}. Mid-range macros across all six axes; "
                "no contract tag (hybrids sit between corners by design)."
            ),
        },
        "seed": "0x5F5F5F5F5F5F5F5F",
        "macros": {
            "tension": _vary(rng, 0.5, 0.4, 0.6, 0.1),
            "damping": _vary(rng, 0.3, 0.2, 0.4, 0.1),
            "density": _vary(rng, 0.55, 0.45, 0.65, 0.1),
            "migration": _vary(rng, 0.3, 0.1, 0.5, 0.2),
            "coherence": _vary(rng, 0.7, 0.5, 0.9, 0.15),
            "excitation": _vary(rng, 0.3, 0.15, 0.45, 0.15),
        },
        "structural": {
            "topology": rng.choice(["ring", "torus_32"]),
            "aspect": 1.0,
            "substrate_size": 1024,
            "deposit_kernel": "linear",
            "read_kernel": "linear",
        },
        "agents": {
            "max_active": 14,
            "harmonic_set": [1, 1.5, 2, 2.5, 3, 4, 5, 7],
            "shape_distribution": {"sine": 0.7, "saw": 0.0, "square": 0.0, "fmpair": 0.2, "noise": 0.1},
            "shape_param_default": {"fm_ratio_index": 0.5, "fm_index_index": 0.35},
            "detune_scale": 0.05,
        },
        "envelopes": {
            "env1": {"attack": 0.1, "decay": 0.4, "sustain": 0.8, "release": 1.5},
            "env2": {"attack": 0.05, "decay": 0.3, "sustain": 1.0, "release": 0.5},
        },
        "lfos": [
            {"rate_hz": _vary(rng, 0.15, 0.05, 0.3, 0.12), "depth": 1.0, "shape": "sine",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": _vary(rng, 0.3, 0.15, 0.6, 0.2), "depth": 1.0, "shape": "triangle",
             "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 5.0, "depth": 1.0, "shape": "sine", "sync": "free", "phase": 0.0, "reset_on_note": False},
            {"rate_hz": 7.0, "depth": 1.0, "shape": "sample_hold", "sync": "free", "phase": 0.0, "reset_on_note": False},
        ],
        "modulation_matrix": {
            "slots": [
                {"active": True, "source": "LFO1", "destination": "MIGRATION",
                 "depth": _vary(rng, 0.2, 0.1, 0.3, 0.1), "curve": "LINEAR"},
                {"active": True, "source": "LFO2", "destination": "EXCITATION",
                 "depth": _vary(rng, 0.2, 0.1, 0.3, 0.1), "curve": "LINEAR"},
            ]
        },
        "harvesters": {"spacing": 0.5, "orbit_depth": 0.0, "orbit_speed_hz": 0.05, "orbit_shape": "circle"},
        "output": {"master_gain_db": 0.0, "pan": 0.0, "limiter_active": False},
    }


TEMPLATES = {
    "drone":   template_drone,
    "organic": template_organic,
    "pitched": template_pitched,
    "glitch":  template_glitch,
    "hybrid":  template_hybrid,
}


def main() -> int:
    factory = ROOT / "presets" / "factory"
    if not factory.is_dir():
        print(f"factory dir not found: {factory}", file=sys.stderr)
        return 1
    written = 0
    for corner, cfg in CORNERS.items():
        out_dir = factory / cfg["dir"]
        out_dir.mkdir(parents=True, exist_ok=True)
        template_fn = TEMPLATES[corner]
        for slot in cfg["slots"]:
            rng = random.Random(slot)  # deterministic seed
            preset = template_fn(slot, rng)
            path = out_dir / f"{slot:03d}_{corner}_filler_{slot}.sfs"
            with open(path, "w") as f:
                json.dump(preset, f, indent=2)
                f.write("\n")
            written += 1
    print(f"Wrote {written} filler presets.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
